/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "background": "#f9f9f9",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#768599",
        "outline": "#747878",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c8c6c6",
        "inverse-primary": "#c8c6c5",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#b9c8de",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#39485a",
        "on-primary-fixed": "#1c1b1b",
        "surface": "#f9f9f9",
        "primary": "#000000",
        "outline-variant": "#c4c7c7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "inverse-surface": "#2f3131",
        "tertiary-fixed": "#d4e4fa",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#464747",
        "on-surface": "#1a1c1c",
        "on-primary-container": "#858383",
        "on-secondary-container": "#646464",
        "inverse-on-surface": "#f1f1f1",
        "primary-fixed": "#e5e2e1",
        "on-secondary-fixed": "#1b1c1c",
        "secondary-fixed": "#e4e2e2",
        "secondary": "#5e5e5e",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#474646",
        "primary-fixed-dim": "#c8c6c5",
        "on-background": "#1a1c1c",
        "primary-container": "#1c1b1b",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#0d1c2d",
        "tertiary-container": "#0d1c2d",
        "on-primary": "#ffffff",
        "on-surface-variant": "#444748",
        "tertiary": "#000000",
        "surface-container": "#eeeeee",
        "secondary-container": "#e4e2e2",
        "surface-tint": "#5f5e5e",
        "surface-dim": "#dadada",
        "surface-border": "#E5E5E5",
        "body-text": "#333333",
        "surface-secondary": "#F5F5F5",
        "accent-blue-soft": "#E6F0FF",
        "accent": "#0066FF",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        "ambient": "0 8px 30px rgba(0,0,0,0.04)"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "24px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "margin-x": "32px",
        "gutter": "32px",
        "section-gap": "160px",
        "section-padding": "120px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "48px",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "h1-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "hero-lg": ["Plus Jakarta Sans", "sans-serif"],
        "subheading": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "h1": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "h2": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "hero-mobile": ["56px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "hero-lg": ["110px", { lineHeight: "100px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "subheading": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
